--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2
-- Dumped by pg_dump version 14.2

-- Started on 2022-04-19 10:50:38

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE membresia;
--
-- TOC entry 3350 (class 1262 OID 16661)
-- Name: membresia; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE membresia WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'Spanish_El Salvador.1252';


\connect membresia

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- TOC entry 209 (class 1259 OID 16662)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- TOC entry 211 (class 1259 OID 16668)
-- Name: permiso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permiso (
    id integer NOT NULL,
    tipo character varying NOT NULL,
    controlador character varying NOT NULL,
    accion character varying NOT NULL
);


--
-- TOC entry 210 (class 1259 OID 16667)
-- Name: permiso_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permiso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permiso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 16676)
-- Name: rol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rol (
    id integer NOT NULL,
    nombre character varying NOT NULL
);


--
-- TOC entry 212 (class 1259 OID 16675)
-- Name: rol_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16691)
-- Name: rol_permiso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rol_permiso (
    id_rol integer NOT NULL,
    id_permiso integer NOT NULL
);


--
-- TOC entry 215 (class 1259 OID 16684)
-- Name: usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario (
    id integer NOT NULL,
    nombre character varying NOT NULL,
    password character varying NOT NULL,
    refresh_token character varying DEFAULT ''::character varying,
    refresh_token_expiracion timestamp without time zone DEFAULT '-infinity'::timestamp without time zone
);


--
-- TOC entry 214 (class 1259 OID 16683)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16706)
-- Name: usuario_rol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_rol (
    id_usuario integer NOT NULL,
    id_rol integer NOT NULL
);


--
-- TOC entry 3189 (class 2606 OID 16666)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3191 (class 2606 OID 16674)
-- Name: permiso pk_permiso; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permiso
    ADD CONSTRAINT pk_permiso PRIMARY KEY (id);


--
-- TOC entry 3193 (class 2606 OID 16682)
-- Name: rol pk_rol; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT pk_rol PRIMARY KEY (id);


--
-- TOC entry 3198 (class 2606 OID 16695)
-- Name: rol_permiso pk_rol_permiso; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT pk_rol_permiso PRIMARY KEY (id_rol, id_permiso);


--
-- TOC entry 3195 (class 2606 OID 16690)
-- Name: usuario pk_usuario; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT pk_usuario PRIMARY KEY (id);


--
-- TOC entry 3201 (class 2606 OID 16710)
-- Name: usuario_rol pk_usuario_rol; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT pk_usuario_rol PRIMARY KEY (id_usuario, id_rol);


--
-- TOC entry 3196 (class 1259 OID 16721)
-- Name: IX_rol_permiso_id_permiso; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_rol_permiso_id_permiso" ON public.rol_permiso USING btree (id_permiso);


--
-- TOC entry 3199 (class 1259 OID 16722)
-- Name: IX_usuario_rol_id_rol; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_usuario_rol_id_rol" ON public.usuario_rol USING btree (id_rol);


--
-- TOC entry 3202 (class 2606 OID 16696)
-- Name: rol_permiso FK_rol_permiso_permiso_id_permiso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT "FK_rol_permiso_permiso_id_permiso" FOREIGN KEY (id_permiso) REFERENCES public.permiso(id) ON DELETE CASCADE;


--
-- TOC entry 3203 (class 2606 OID 16701)
-- Name: rol_permiso FK_rol_permiso_rol_id_rol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT "FK_rol_permiso_rol_id_rol" FOREIGN KEY (id_rol) REFERENCES public.rol(id) ON DELETE CASCADE;


--
-- TOC entry 3204 (class 2606 OID 16711)
-- Name: usuario_rol FK_usuario_rol_rol_id_rol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT "FK_usuario_rol_rol_id_rol" FOREIGN KEY (id_rol) REFERENCES public.rol(id) ON DELETE CASCADE;


--
-- TOC entry 3205 (class 2606 OID 16716)
-- Name: usuario_rol FK_usuario_rol_usuario_id_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT "FK_usuario_rol_usuario_id_usuario" FOREIGN KEY (id_usuario) REFERENCES public.usuario(id) ON DELETE CASCADE;


-- Completed on 2022-04-19 10:50:38

--
-- PostgreSQL database dump complete
--

